spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tj_db?allowPublicKeyRetrieval=true&useSSL=false
    username: testuser
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        '[format_sql]': true
  data:
    redis:
      host: localhost
      port: 6379
      password: # Optional, uncomment and set if Redis requires authentication

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
  api-docs:
    path: /v3/api-docs
  packages-to-scan: com.gs.tj.controller
  paths-to-match: /**
  show-actuator: false
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  disable-swagger-default-url: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.springframework: INFO
    com.gs.tj: DEBUG
    org.springdoc: DEBUG
    org.springdoc.api: TRACE 